"""
Alert Models

Defines the structure for correlated alerts generated by the engine.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from uuid import uuid4

from pydantic import BaseModel, Field

from correlation_engine.models.event import EventSeverity, SecurityEvent


class AlertPriority(str, Enum):
    """Alert priority levels for triage."""

    P1_CRITICAL = "p1_critical"  # Immediate action required
    P2_HIGH = "p2_high"  # Action within 1 hour
    P3_MEDIUM = "p3_medium"  # Action within 4 hours
    P4_LOW = "p4_low"  # Action within 24 hours
    P5_INFORMATIONAL = "p5_informational"  # For reporting only

    @property
    def numeric_value(self) -> int:
        """Return numeric value for comparison."""
        return {
            "p1_critical": 1,
            "p2_high": 2,
            "p3_medium": 3,
            "p4_low": 4,
            "p5_informational": 5,
        }[self.value]


class AlertStatus(str, Enum):
    """Alert lifecycle status."""

    NEW = "new"
    IN_REVIEW = "in_review"
    INVESTIGATING = "investigating"
    ESCALATED = "escalated"
    RESOLVED = "resolved"
    FALSE_POSITIVE = "false_positive"
    DISMISSED = "dismissed"


class AlertCategory(str, Enum):
    """Categories for alert classification."""

    BRUTE_FORCE = "brute_force"
    MALWARE = "malware"
    DATA_EXFILTRATION = "data_exfiltration"
    LATERAL_MOVEMENT = "lateral_movement"
    PRIVILEGE_ESCALATION = "privilege_escalation"
    ACCOUNT_COMPROMISE = "account_compromise"
    POLICY_VIOLATION = "policy_violation"
    ANOMALY = "anomaly"
    INSIDER_THREAT = "insider_threat"
    EXTERNAL_ATTACK = "external_attack"
    MISCONFIGURATION = "misconfiguration"
    OTHER = "other"


class Alert(BaseModel):
    """
    Represents a correlated alert generated by the correlation engine.

    Alerts are created when events match correlation rules and may
    combine multiple related events into a single actionable item.
    """

    alert_id: str = Field(default_factory=lambda: str(uuid4()))
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # Alert classification
    title: str
    description: str
    category: AlertCategory = AlertCategory.OTHER
    priority: AlertPriority = AlertPriority.P4_LOW
    severity: EventSeverity = EventSeverity.MEDIUM
    status: AlertStatus = AlertStatus.NEW

    # Related events
    events: list[SecurityEvent] = Field(default_factory=list)
    event_ids: list[str] = Field(default_factory=list)

    # Correlation details
    rule_id: Optional[str] = None
    rule_name: Optional[str] = None
    correlation_score: float = Field(ge=0.0, le=1.0, default=0.5)

    # Entity information (deduplicated from events)
    src_ips: list[str] = Field(default_factory=list)
    dst_ips: list[str] = Field(default_factory=list)
    users: list[str] = Field(default_factory=list)
    hosts: list[str] = Field(default_factory=list)

    # Timeline
    first_event_time: Optional[datetime] = None
    last_event_time: Optional[datetime] = None
    event_count: int = 0

    # False positive handling
    is_false_positive: bool = False
    false_positive_reason: Optional[str] = None
    whitelist_match: Optional[str] = None

    # Response tracking
    assignee: Optional[str] = None
    notes: list[dict[str, Any]] = Field(default_factory=list)
    timeline: list[dict[str, Any]] = Field(default_factory=list)

    # MITRE ATT&CK mapping
    mitre_tactics: list[str] = Field(default_factory=list)
    mitre_techniques: list[str] = Field(default_factory=list)

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "alert_id": "alert-001",
                    "title": "Brute Force Attack Detected",
                    "description": "Multiple failed login attempts from 192.168.1.100",
                    "category": "brute_force",
                    "priority": "p2_high",
                    "severity": "high",
                    "src_ips": ["192.168.1.100"],
                    "users": ["admin"],
                    "event_count": 50,
                    "mitre_tactics": ["Credential Access"],
                    "mitre_techniques": ["T1110.001"],
                }
            ]
        }
    }

    def add_event(self, event: SecurityEvent) -> None:
        """Add an event to this alert and update aggregated fields."""
        if event.event_id in self.event_ids:
            return

        self.events.append(event)
        self.event_ids.append(event.event_id)
        self.event_count = len(self.events)

        # Update timestamp range
        if self.first_event_time is None or event.timestamp < self.first_event_time:
            self.first_event_time = event.timestamp
        if self.last_event_time is None or event.timestamp > self.last_event_time:
            self.last_event_time = event.timestamp

        # Update entity lists
        if event.src_ip and event.src_ip not in self.src_ips:
            self.src_ips.append(event.src_ip)
        if event.dst_ip and event.dst_ip not in self.dst_ips:
            self.dst_ips.append(event.dst_ip)
        if event.src_user and event.src_user not in self.users:
            self.users.append(event.src_user)
        if event.dst_user and event.dst_user not in self.users:
            self.users.append(event.dst_user)
        if event.src_host and event.src_host not in self.hosts:
            self.hosts.append(event.src_host)
        if event.dst_host and event.dst_host not in self.hosts:
            self.hosts.append(event.dst_host)

        self.updated_at = datetime.now(timezone.utc)

    def add_note(self, note: str, author: str = "system") -> None:
        """Add a note to the alert."""
        self.notes.append(
            {"timestamp": datetime.now(timezone.utc).isoformat(), "author": author, "note": note}
        )
        self.updated_at = datetime.now(timezone.utc)

    def mark_false_positive(self, reason: str, whitelist_rule: Optional[str] = None) -> None:
        """Mark this alert as a false positive."""
        self.is_false_positive = True
        self.false_positive_reason = reason
        self.whitelist_match = whitelist_rule
        self.status = AlertStatus.FALSE_POSITIVE
        self.add_note(f"Marked as false positive: {reason}")

    def calculate_priority(self) -> AlertPriority:
        """
        Calculate alert priority based on multiple factors.

        Factors considered:
        - Event severity
        - Event count
        - Correlation score
        - Category risk level
        """
        base_score = 0

        # Severity contribution (0-30 points)
        severity_scores = {
            EventSeverity.CRITICAL: 30,
            EventSeverity.HIGH: 20,
            EventSeverity.MEDIUM: 10,
            EventSeverity.LOW: 5,
        }
        base_score += severity_scores.get(self.severity, 5)

        # Event count contribution (0-25 points)
        if self.event_count >= 100:
            base_score += 25
        elif self.event_count >= 50:
            base_score += 20
        elif self.event_count >= 20:
            base_score += 15
        elif self.event_count >= 10:
            base_score += 10
        elif self.event_count >= 5:
            base_score += 5

        # Correlation score contribution (0-25 points)
        base_score += int(self.correlation_score * 25)

        # Category risk contribution (0-20 points)
        high_risk_categories = {
            AlertCategory.ACCOUNT_COMPROMISE,
            AlertCategory.MALWARE,
            AlertCategory.DATA_EXFILTRATION,
            AlertCategory.LATERAL_MOVEMENT,
        }
        medium_risk_categories = {
            AlertCategory.BRUTE_FORCE,
            AlertCategory.PRIVILEGE_ESCALATION,
            AlertCategory.INSIDER_THREAT,
        }

        if self.category in high_risk_categories:
            base_score += 20
        elif self.category in medium_risk_categories:
            base_score += 10

        # Map score to priority
        if base_score >= 80:
            return AlertPriority.P1_CRITICAL
        elif base_score >= 60:
            return AlertPriority.P2_HIGH
        elif base_score >= 40:
            return AlertPriority.P3_MEDIUM
        elif base_score >= 20:
            return AlertPriority.P4_LOW
        else:
            return AlertPriority.P5_INFORMATIONAL

    def to_dict(self) -> dict[str, Any]:
        """Convert alert to dictionary for serialization."""
        return {
            "alert_id": self.alert_id,
            "title": self.title,
            "description": self.description,
            "category": self.category.value,
            "priority": self.priority.value,
            "severity": self.severity.value,
            "status": self.status.value,
            "event_count": self.event_count,
            "src_ips": self.src_ips,
            "dst_ips": self.dst_ips,
            "users": self.users,
            "hosts": self.hosts,
            "correlation_score": self.correlation_score,
            "rule_id": self.rule_id,
            "rule_name": self.rule_name,
            "first_event_time": self.first_event_time.isoformat()
            if self.first_event_time
            else None,
            "last_event_time": self.last_event_time.isoformat()
            if self.last_event_time
            else None,
            "is_false_positive": self.is_false_positive,
            "mitre_tactics": self.mitre_tactics,
            "mitre_techniques": self.mitre_techniques,
        }
